### ISSUE TITLE
New update fails to download

### ISSUE THREAD

**Issue by ljcool2006** [shadowscion/sprops#1]
You might as well revert to the previous version of SProps while you are fixing the issue.

**Comment by shadowscion** [comment]
Restart gmod

**Comment by hobnob11** [comment]
![image](https://user-images.githubusercontent.com/2287055/114376179-4b365000-9b7d-11eb-81d3-65610323c6f7.png)
can we reopen this issue, because on both my servers and client sprops now refuses to download, maybe a corrupted workshop upload?

**Comment by shadowscion** [comment]
If there's a problem, that's an issue for one of the garrysmod github pages, nothing I can do.
